name: CI/CD Pipeline with OWASP ZAP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test

  security_scan:
    runs-on: ubuntu-latest

    services:
      app:
        image: your-docker-image:latest # Replace with your application Docker image
        ports:
          - 3000:3000
        options: --name app-container

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Wait for application to start
      - name: Wait for application
        run: |
          echo "Waiting for the application to start..."
          for i in {1..10}; do
            curl -s http://localhost:3000 && break
            echo "Waiting..."
            sleep 5
          done

      # Step 3: Run OWASP ZAP Security Scan
      - name: Run OWASP ZAP Security Scan
        uses: zaproxy/action-full-scan@v0.6.0
        env:
          ZAP_DISABLE_ADDONS: 'true' # Optional: Disable auto add-on updates
        with:
          target: 'http://app-container:3000'  # Use Docker container name as hostname
          timeout: 600                         # Extend timeout to 10 minutes
          rules: WARN                          # Continue on warnings
          report: true                         # Generate HTML, JSON, and MD reports

      # Step 4: Upload ZAP Reports
      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v3
        with:
          name: zap-reports
          path: |
            report_html.html   # HTML report
            report_json.json   # JSON report
            report_md.md       # Markdown report
