name: CI/CD Pipeline with OWASP ZAP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test

  security_scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Run OWASP ZAP Security Scan
      - name: Run OWASP ZAP Security Scan
        uses: zaproxy/action-full-scan@v0.6.0
        with:
          target: 'http://localhost:3000'  # Replace with the URL of your application
          rules: WARN                     # Optional: Continue with warnings
          report: true                    # Generate detailed HTML report

      # Step 3: Upload ZAP Report as Artifact
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: /zap/wrk/spider_report.html   # Path to save the generated report from ZAP
